### PR TITLE
Updates to code descriptions output by HELP with minor refactor

### PR DESCRIPTION
**Pull request by noobydp**
I noticed that you modified the HELP code so that it includes the 'standard' g/mcodes.
I have added reasonable descriptions for each of the codes (as much as possible).

I have done basic testing on a small desktop 3 axis CNC machine, but have not run large/complex jobs.
The changes should be relatively safe IMO.

For reference - I'm creating a custom Fusion 360 Post Processor and might end up with custom posts for vanilla klipper vs klipper-for-cnc. I wanted a comparison of the g/mcodes available in each, and stumbled across the HELP function... which led to this.
I assume there's no wide-spread need for this to be accurate, but figured it couldnt hurt.

### CODE REVIEW

**Comment by afbenevides** [comment]
@noobydp that seems interesting, do you plan on sharing those post- processor? I will be starting a small CNC build based on the klipper-for-cnc, and I would have interest in working on available posts for Processor if available.

**Comment by noobydp** [comment]
@afbenevides i sure can, but I'll probably be a few more weeks until I can finish. 

Right now I'm using this MPCNC PP, it works fine but I wanted to make one that's more specific for Klipper, and add some features. 

https://github.com/flyfisher604/mpcnc_post_processor

**Comment by afbenevides** [comment]
Thanks for the link.

**Comment by naikymen** [comment]
Done :) thanks a lot!

I made small changes before merging: b455ef3e062e3edba2024adddc8455027be0b987

The most important being moving M114 and GET_POSITION out of the handlers list. Those required `when_not_ready=True`.

**Pull request merged**
