### PR TITLE
Added fixed coded support for UVW, axis

### PR DESCRIPTION
**Pull request by JordyDH**
I have extended the code to support an additional UVW axes.
I'm currently in the works to have a generic method to add as many axes that you want (max 26).

### CODE REVIEW

**Comment by JordyDH** [comment]
A max of 26 is not possible when you want to use also extruder.
Maybe set the max limit to 23 axis and skip the letter E?

**Comment by naikymen** [comment]
Have you already tested this in hardware?

I would be very happy to learn that this PR was really enough. I really tried to generalize my changes elsewhere in the code, specially in the probing and homing parts.

Note that the GCODE arcs extra will require attention in a future PR. I have not done a great job with it.

**Comment by naikymen** [comment]
Another matter is how acceleration should "shared" between axes. Have you pondered on that already?

**Comment by JordyDH** [comment]
I think we need to make the decision to be compatible with the klipper base system.
My perspective on this is to modify what is needed to make klipper work for multi axis synchronous machines.

I will personally remove the Extruder logic from the kinematics, right now klipper adds the extruder on its own.
Not all machines have an extruder, so why not change the behavior that the user can choose to opt in.

I quicky asked GPT to name more axis in the same name scheme of XYZ ABC UVW and I got this:

> Certainly! I'll generate sets of three-letter axis groups that sound logical and follow the convention we discussed (XYZ,
> ABC, UVW, PQR). I'll extend the sequence while maintaining the pattern :
> XYZ
> ABC
> UVW
> PQR
> DEF
> GHI
> JKL
> MNO
> STU

We can also do a simple generator script to create the alphabet and then remove the not wanted letters from it.
Also, 'F' is one that needs to be removed because it is used for the feedrate.

We have tested this branch, and it works for us, but to be honest I wouldn't merge.
I'm working on a more elegant way to include the multiple kinematic models and make it auto extend to a more than 9 axis (with all the features working, homing, different feedrates, different accelerations, and etc.).

I think for multi axis machines, we want to have different accelerations as an option available.

This is a bigger problem, especially if we want to make a “generic” model that works with a lot of different machines.
One solution is to think about different kinematic models for multi axis, with each their set of features and limitation.

**Comment by JordyDH** [comment]
The reason for closing this PR is that I'm going to make a separate branch on my repo for this specific problem.

**Comment by naikymen** [comment]
> Also, 'F' is one that needs to be removed because it is used for the feedrate.

Sounds right!

Remember that the letter S is also reserved for spindle power/speed: https://marlinfw.org/docs/gcode/G000-G001.html

Will you be opening another PR?

**Pull request closed without merging**
